Procrastinator/Controllers/InfoViewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Procrastinator.Models;
using Procrastinator.Models.ViewModels;
using Procrastinator.Settings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Procrastinator.Controllers
{
    public class InfoViewController : Controller
    {
        ProcrastinatorContext db;
        public InfoViewController(ProcrastinatorContext context)
        {
            Config.SidebarVisible = false;
            db = context;
            
            // An exemple of adding initial data
            //if (db.GymCoaches.Count() == 0)
            //{
            //    GymCoach ivanov = new GymCoach { Id = 1, LastName="Ivanov" };
            //    GymCoach petrov = new GymCoach { Id = 2, LastName = "Petrov" };
            //    GymCoach sidorov = new GymCoach { Id = 3, LastName = "Sidorov" };
            //                    
            //
            //    GymVisitor visitor1 = new GymVisitor { Id=1, FirstName="Alex", LastName="Saint", Phone="+380962213", CoachId=1 };
            //    GymVisitor visitor2 = new GymVisitor { Id=2, FirstName="Pavel", LastName="Rudenko", Phone="+380962213", CoachId=1 };
            //    
            //
            //    db.GymCoaches.AddRange(ivanov, petrov, sidorov);
            //    db.GymVisitors.AddRange(visitor1, visitor2);
            //    db.SaveChanges();
            //}
        }
        public ActionResult Index(int? coach, string name, SortState sortOrder = SortState.NameAsc)
        {
            ViewBag.Title = "Visitors info";
            //IQueryable<GymVisitor> users = db.GymVisitors.Include(p => p.CoachId);
            IQueryable<GymVisitor> users = db.GymVisitors.Where(p => p.CoachId != null);
            ViewData["NameSort"] = sortOrder == SortState.NameAsc ? SortState.NameDesc : SortState.NameAsc;
            users = sortOrder switch
            {
                SortState.NameDesc => users.OrderByDescending(s => s.LastName),
                SortState.CompanyAsc => users.OrderBy(s => s.LastName),
                SortState.CompanyDesc => users.OrderByDescending(s => s.LastName),
                _ => users.OrderBy(s => s.LastName),
            };

            if (coach != null && coach != 0)
            {
                users = users.Where(p => p.CoachId == coach);
            }
            if (!String.IsNullOrEmpty(name))
            {
                users = users.Where(p => p.LastName.Contains(name));
            }

            List<GymCoach> coaches = db.GymCoaches.ToList();
            // устанавливаем начальный элемент, который позволит выбрать всех
            coaches.Insert(0, new GymCoach { Id = 0, LastName = "All" });
            

            InfoVIewModel viewModel = new InfoVIewModel
            {
                GymVisitors = users.ToList(),
                Coaches = new SelectList(coaches, "Id", "LastName"),
                SecondName = name,
                GymCoaches = coaches
               
            };

            
            return View(viewModel);
        }
        public async Task<IActionResult> Sort(SortState sortOrder = SortState.NameAsc)
        {
            IQueryable<GymVisitor> users = db.GymVisitors.Where(x => x.CoachId!=null);

            ViewData["NameSort"] = sortOrder == SortState.NameAsc ? SortState.NameDesc : SortState.NameAsc;
            

            users = sortOrder switch
            {
                SortState.NameDesc => users.OrderByDescending(s => s.LastName),
                SortState.CompanyAsc => users.OrderBy(s => s.LastName),
                SortState.CompanyDesc => users.OrderByDescending(s => s.LastName),
                _ => users.OrderBy(s => s.LastName),
            };
            return View(await users.AsNoTracking().ToListAsync());
        }
        public IActionResult Pie()
        {
            ViewBag.Title = "Coaches and their clients";
            Random rnd = new Random();
            IQueryable<GymCoach> coaches = db.GymCoaches.Where(p => p.LastName != null);


            var lstModel = new List<SimpleReportViewModel>();
            foreach(GymCoach coach in coaches)
            {
                lstModel.Add(new SimpleReportViewModel
                {
                    DimensionOne = coach.LastName,
                    Quantity = db.GymVisitors.Where(a => a.CoachId == coach.Id).Count()
                }); 
            }
            
            return View(lstModel);
        }
        
    }
}

Procrastinator/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
@if (@Config.UseBootstrap)
{
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
}

Procrastinator/Views/Shared/FooterPartial.cshtml
<section id="footer" class="wrapper">
    <div class="title">The Rest Of It</div>
    <div class="container">
        <header class="style1">
            <h2>Ipsum sapien elementum portitor?</h2>
            <p>
                Sed turpis tortor, tincidunt sed ornare in metus porttitor mollis nunc in aliquet.<br />
                Nam pharetra laoreet imperdiet volutpat etiam feugiat.
            </p>
        </header>
        <div class="row">
            <div class="col-6 col-12-medium">

                <!-- Contact Form -->
                <section>
                    <form method="post" action="#">
                        <div class="row gtr-50">
                            <div class="col-6 col-12-small">
                                <input type="text" name="name" id="contact-name" placeholder="Name" />
                            </div>
                            <div class="col-6 col-12-small">
                                <input type="text" name="email" id="contact-email" placeholder="Email" />
                            </div>
                            <div class="col-12">
                                <textarea name="message" id="contact-message" placeholder="Message" rows="4"></textarea>
                            </div>
                            <div class="col-12">
                                <ul class="actions">
                                    <li><input type="submit" class="style1" value="Send" /></li>
                                    <li><input type="reset" class="style2" value="Reset" /></li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </section>

            </div>
            <div class="col-6 col-12-medium">

                <!-- Contact -->
                <section class="feature-list small">
                    <div class="row">
                        <div class="col-6 col-12-small">
                            <section>
                                <h3 class="icon solid fa-home">Mailing Address</h3>
                                <p>
                                    @MyInfo.Name<br />
                                    @MyInfo.Email<br />
                                    @MyInfo.City<br />
                                    @MyInfo.Country<br />
                                </p>
                            </section>
                        </div>
                        <div class="col-6 col-12-small">
                            <section>
                                <h3 class="icon solid fa-comment">Social</h3>
                                <p>
                                    <a href="@MyInfo.LinkedIn">LinkedIn</a>
                                    <br />
                                    <a href="@MyInfo.FaceBook">FaceBook</a>
                                    
                                </p>
                            </section>
                        </div>
                        <div class="col-6 col-12-small">
                            <section>
                                <h3 class="icon solid fa-envelope">Email</h3>
                                <p>
                                    <a href="#">info@untitled.tld</a>
                                </p>
                            </section>
                        </div>
                        <div class="col-6 col-12-small">
                            <section>
                                <h3 class="icon solid fa-phone">Phone</h3>
                                <p>
                                    (000) 555-0000
                                </p>
                            </section>
                        </div>
                    </div>
                </section>

            </div>
        </div>
        <div id="copyright">
            <ul>
                <li>&copy; Untitled.</li>
                <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
            </ul>
        </div>
    </div>
</section>

Procrastinator/Views/Shared/HeaderPartial.cshtml
<section id="header" class="wrapper">

    <!-- Logo -->
    <div id="logo">
        <h1><a asp-controller="Home" asp-action="Index">Data Viewer</a></h1>
        <p>Made by @MyInfo.Name</p>
        
    </div>

    <!-- Nav -->
    <nav id="nav">
        <ul>
            <li><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li><a asp-controller="InfoView" asp-action="Index">Data Viewer</a></li>
            <li><a asp-controller="Home" asp-action="Contacts">Contacts</a></li>
            <li><a asp-controller="InfoView" asp-action="Pie">Chart</a></li>
            <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
        </ul>
    </nav>

</section>

Procrastinator/Views/Shared/HighlightsPartial.cshtml
<section id="highlights" class="wrapper style3">
    <div class="title">The Endorsements</div>
    <div class="container">
        <div class="row aln-center">
            <div class="col-4 col-12-medium">
                <section class="highlight">
                    <a href="#" class="image featured"><img src="images/pic02.jpg" alt="" /></a>
                    <h3><a href="#">Aliquam diam consequat</a></h3>
                    <p>Eget mattis at, laoreet vel amet sed velit aliquam diam ante, dolor aliquet sit amet vulputate mattis amet laoreet lorem.</p>
                    <ul class="actions">
                        <li><a href="#" class="button style1">Learn More</a></li>
                    </ul>
                </section>
            </div>
            <div class="col-4 col-12-medium">
                <section class="highlight">
                    <a href="#" class="image featured"><img src="images/pic03.jpg" alt="" /></a>
                    <h3><a href="#">Nisl adipiscing sed lorem</a></h3>
                    <p>Eget mattis at, laoreet vel amet sed velit aliquam diam ante, dolor aliquet sit amet vulputate mattis amet laoreet lorem.</p>
                    <ul class="actions">
                        <li><a href="#" class="button style1">Learn More</a></li>
                    </ul>
                </section>
            </div>
            <div class="col-4 col-12-medium">
                <section class="highlight">
                    <a href="#" class="image featured"><img src="images/pic04.jpg" alt="" /></a>
                    <h3><a href="#">Mattis tempus lorem</a></h3>
                    <p>Eget mattis at, laoreet vel amet sed velit aliquam diam ante, dolor aliquet sit amet vulputate mattis amet laoreet lorem.</p>
                    <ul class="actions">
                        <li><a href="#" class="button style1">Learn More</a></li>
                    </ul>
                </section>
            </div>
        </div>
    </div>
</section>

Procrastinator/Views/Shared/JsPartial.cshtml
<script src="~/js/jquery.min.js"></script>
<script src="~/js/jquery.dropotron.min.js"></script>
<script src="~/js/browser.min.js"></script>
<script src="~/js/breakpoints.min.js"></script>
<script src="~/js/util.js"></script>
<script src="~/js/main.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>    

Procrastinator/Views/Shared/SidebarPartial.cshtml
<div id="sidebar">
    <section class="box">
        <header>
            <h2>Ipsum nullam luctus</h2>
        </header>
        <p>
            Malesuada quis eget eros. Nullam sodales cursus sapien, id consequat
            leo suscipit ut. Praesent id turpis vitae turpis pretium ultricies. Vestibulum sit
            amet risus elit.
        </p>
        <a href="#" class="button style1">Learn More</a>
    </section>
    
</div>

Procrastinator/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>

<html>
<head>
    @if (@ViewBag.Title != null)
    {
        <title>@ViewBag.Title</title>
    }
    else
    {
        <title>@MyInfo.Name</title>
    }
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    @await Html.PartialAsync("CssPArtial")
</head>
<body class="right-sidebar is-preload">
    <div id="page-wrapper">

        <!-- Header -->
        @await Html.PartialAsync("HeaderPartial")

        <!-- Main -->
        <section id="main" class="wrapper style2">
            <div class="title">@ViewBag.title</div>
            <div class="container">
                <div class="row gtr-150">
                    <div class="col-8 col-12-medium">

                        <!-- Content -->
                        @RenderBody()
                        <div id="content">
                            <article class="box post">
                                <header class="style1">
                                    <h2>Lorem ipsum dolor sit amet magna egestas morbi bibendum sed malesuada</h2>
                                    <p>Tempus feugiat veroeros sed nullam dolore</p>
                                </header>
                                <a href="#" class="image featured">
                                    <img src="images/pic01.jpg" alt="" />
                                </a>
                                <p>
                                    Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget.
                                    odio eleifend. Duis commodo fringilla commodo. Aliquam erat volutpat. Vestibulum
                                    facilisis leo magna. Cras sit amet urna eros, id egestas urna. Quisque aliquam
                                    tempus euismod. Vestibulum ante ipsum primis in faucibus.
                                </p>
                                <p>
                                    Phasellus nisl nisl, varius id porttitor sed, pellentesque ac orci. Pellentesque
                                    habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi
                                    bibendum justo sed mauris vehicula malesuada aliquam elit imperdiet. Aliquam eu nibh
                                    lorem, eget gravida mi. Duis odio diam, luctus et vulputate vitae, vehicula ac dolor.
                                    Pellentesque at urna eget tellus lobortis ultrices sed non erat. Donec eget erat non
                                    magna volutpat malesuada quis eget eros. Nullam sodales cursus sapien, id consequat
                                    leo suscipit ut. Praesent id turpis vitae turpis pretium ultricies. Vestibulum sit
                                    amet risus elit.
                                </p>
                                <p>
                                    Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra
                                    ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel. Praesent nec orci
                                    eget quam rutrum bibendum. Proin pellentesque diam non ligula commodo tempor. Vivamus
                                    eget urna nibh. Curabitur non fringilla nisl. Donec accumsan interdum nisi, quis
                                    tincidunt felis sagittis eget. Donec elementum ligula dignissim sem pulvinar non semper
                                    odio eleifend. Duis commodo fringilla commodo. Aliquam erat volutpat. Vestibulum
                                    facilisis leo magna. Cras sit amet urna eros, id egestas urna. Quisque aliquam
                                    tempus euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
                                    posuere cubilia.
                                </p>
                                <p>
                                    Phasellus nisl nisl, varius id porttitor sed, pellentesque ac orci. Pellentesque
                                    habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi
                                    bibendum justo sed mauris vehicula malesuada aliquam elit imperdiet. Aliquam eu nibh
                                    lorem, eget gravida mi. Duis odio diam, luctus et vulputate vitae, vehicula ac dolor.
                                    Pellentesque at urna eget tellus lobortis ultrices sed non erat. Donec eget erat non
                                    magna volutpat malesuada quis eget eros. Nullam sodales cursus sapien, id consequat
                                    leo suscipit ut. Praesent id turpis vitae turpis pretium ultricies. Vestibulum sit
                                    amet risus elit.
                                </p>
                            </article>
                            
                        </div>

                    </div>
                    @if (Config.SidebarVisible)
                    {
                        <div class="col-4 col-12-medium">

                            <!-- Sidebar -->

                            @await Html.PartialAsync("SidebarPartial")




                        </div>
                    }

                </div>
            </div>
        </section>

        <!-- Highlights -->
        <!-- Footer -->
        @await Html.PartialAsync("FooterPartial")

    </div>

    <!-- Scripts -->
    @await Html.PartialAsync("JsPartial")

</body>
</html>